source-list-line-count: 1

source-list-keyword-color: "\x1b[0m"
source-list-string-color: "\x1b[34m"
source-list-number-color: "\x1b[0m"
source-list-comment-color: "\x1b[32m"
source-list-arrow-color: "\x1b[90m"
source-list-line-color: "\x1b[90m"
source-list-tab-color: "\x1b[0m"

tab: '    '
