#!/bin/sh

# Prepend branch name to the commit message if branch named like a
# bugtracker task id (e.g. ID-123456).

TASKID=$(git branch --show-current | grep -Eo "\w+-\d+")
test -z "$TASKID" && exit 0
grep -s -v "^#" "$1" | grep -qs "$TASKID" || sed -i "" -e "1s/^/[$TASKID] /" "$1"
